### ISSUE TITLE
Re-tag new version

### ISSUE THREAD

**Issue by vivekkj123** [tc39/ecmarkdown#87]
Sorry for opening a new issue again... 

Please re-tag the new version of this npm module in this upstream, since I made some changes in #85...

Regards,

Vivek K J

**Comment by bakkot** [comment]
Hm. There's been no changes to the source of the project itself since the last release. As such, by the conventions of JavaScript packages, there's no call for a release. I appreciate that debian likes to include tests alongside packages, and also wants to have tagged releases of everything, but it seems somewhat impolite to impose that requirement on a community which has different conventions.

**Comment by vivekkj123** [comment]
I am not asking you to make a new release in this repo.. I think you can move/edit the tag(not release) from old to latest commit...

**Comment by bakkot** [comment]
By convention, version number tags point to the corresponding version bump commit. I'm not willing to point it to a different commit.

**Comment by vivekkj123** [comment]
So do I have to wait until the next release? When will be that?

**Comment by vivekkj123** [comment]
Or there will be any minor releases with bugfixes?

**Comment by pravi** [comment]
@vivekkj123 you can include the change as a patch in the debian package. Vivek is new to debian packaging so he is still learning how to create packages. Debian does not want to impose such things on any project. We usually request updating build dependencies but if the project does not want to do it, we include them as patches in debian. But we would really prefer if each project move to recent versions of build tools.

**Comment by bakkot** [comment]
Closing per https://github.com/tc39/ecmarkdown/issues/85#issuecomment-752351870.
